engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
          Controversial/CamelCaseVariableName:
            enabled: false
  phan:
      enabled: true
      config:
        file_extensions: "php"
      checks:
            PhanUndeclaredClassMethod:
              enabled: false

ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- "lib/vlib/"
- "lib/tcpdf/"
- "lib/smarty/"
- "lib/bbcode/"
- "js/"
- "css/"
- "fonts/"
- "icons/"
- "datatables/"
- "locale/"
- "documentation/"
- "templates/custom_css/"
