sudo: false

# Blacklist the github pages branch
branches:
  except:
    - gh-pages

# Environment variables
env:
  global:
    #- GH_REPO_NAME: <your_repo>
    #- DOXYFILE: $TRAVIS_BUILD_DIR/<path_to_your_doxygen_configuration_file>
    #- GH_REPO_REF: github.com/<your_name>/<your_repo>.git

services:
  - mysql

language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
  - nightly

addons:
    code_climate:
        repo_token: 1afb25d82e46d481471a191d4dfb50104b300a2d2c77259e10445bf111a07175

before_install:
   - mysql -e "CREATE DATABASE IF NOT EXISTS test;"

# Install dependencies
#addons:
#  apt:
#    packages:
#      - doxygen
#      - doxygen-doc
#      - doxygen-latex
#      - doxygen-gui
#      - graphviz

before_script:
  - composer require codeclimate/php-test-reporter --dev

# Build your code e.g. by calling make
script:
  #- cd ./development
  # Create an installation .tar.gz package
  #- cd ./tools.sh -p -dev
  # Generate doxygen documentation
  #- cd ./tools.sh -d
  - phpunit --configuration phpunit.xml --coverage-clover build/logs/clover.xml
  - phpunit --configuration phpunit_mysql.xml --coverage-clover build/logs/clover.xml


after_success:
  - vendor/bin/test-reporter